### ISSUE TITLE
error while parsing fasta file

### ISSUE THREAD

**Issue by timosachsenberg** [sangtaekim/msgfplus#12]
Did anyone experience a:
java.lang.ArrayIndexOutOfBoundsException: 223
	at edu.ucsd.msjava.msdbsearch.DBScanner.setAminoAcidProbabilities(DBScanner.java:845)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:189)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:106)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:57)

in the past and has some hints?

**Comment by timosachsenberg** [comment]
ok I found it. A character with ASCII code of 223 was contained in the fasta sequence
