### ISSUE TITLE
mzid conversion crashed

### ISSUE THREAD

**Issue by JB-MS** [sangtaekim/msgfplus#14]
Hi together,

I am using MS-GF+ on a regular basis, but lately I have encountered a problem when converting large mzid files (4.2GB) to tsv with the provided converter. I am using version 2017/01/27, the error is attached below.

OS: CentOS
Java version: "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

Any help is highly appreciated.

Cheers,
Johannes

MzIDToTsv v9108 (27 Jan 2017)
Exception in thread "main" java.lang.IllegalArgumentException: Can not read more than 2147483647 bytes!
        at psidev.psi.tools.xxindex.FastXmlElementExtractor.readBytes(FastXmlElementExtractor.java:180)
        at psidev.psi.tools.xxindex.FastXmlElementExtractor.readString(FastXmlElementExtractor.java:202)
        at psidev.psi.tools.xxindex.StandardXpathAccess$XmlSnippetIterator.next(StandardXpathAccess.java:339)
        at psidev.psi.tools.xxindex.StandardXpathAccess$XmlSnippetIterator.next(StandardXpathAccess.java:293)
        at uk.ac.ebi.jmzidml.xml.io.MzIdentMLUnmarshaller.retrieveFromXML(MzIdentMLUnmarshaller.java:291)
        at uk.ac.ebi.jmzidml.xml.io.MzIdentMLUnmarshaller.doUnmarshal(MzIdentMLUnmarshaller.java:266)
        at uk.ac.ebi.jmzidml.xml.io.MzIdentMLUnmarshaller.unmarshal(MzIdentMLUnmarshaller.java:184)
        at edu.ucsd.msjava.mzid.MzIDParser.writeToTSVFile(MzIDParser.java:60)
        at edu.ucsd.msjava.mzid.MzIDParser.writeToTSVFile(MzIDParser.java:50)
        at edu.ucsd.msjava.ui.MzIDToTsv.convert(MzIDToTsv.java:125)
        at edu.ucsd.msjava.ui.MzIDToTsv.main(MzIDToTsv.java:83)

**Comment by FarmGeek4Life** [comment]
I don't think I can fix that error (it's being caused inside the library used to read mzid files, and will happen for any mzid file over 2GB in size).

A couple of options:

1) If you can copy the file to a Windows system, the zip file that can be downloaded from https://omics.pnl.gov/software/ms-gf contains a C# MzidToTsvConverter that should be able to convert the file (you might be able to run it on Linux using Mono, but I've never tried that).

2) I can compile that converter using .NET Core (with a few modifications), which would run on Linux once the dotnet core packages were installed.

The other benefit of this C# MzidToTsv converter is that it is significantly faster than the one in MSGF+ (because it can read the mzid files more efficiently).

**Comment by FarmGeek4Life** [comment]
Also, seeing some of your other work on GitHub, you might be happy to know that the C# converter can directly read gzipped mzid files, no need to ungzip them first (it's faster if you don't)

**Comment by JB-MS** [comment]
Hi,

thanks for the quick reply! We are mainly using unix systems for our approaches, but will try using Mono for the other converter you mentioned. I'll test it and let you know if it works.

Direct reading of gzip sounds awesome, since compressing and decompressing takes while...

Cheers,
Johannes

**Comment by ypriverol** [comment]
@JB-MS @FarmGeek4Life we have a native converter of mzIDentML to mzTab (tab delimited files). Another possible solution. Have you try to increase the version of jmzIdentML. We did major improvements in the performance of the library.

**Comment by FarmGeek4Life** [comment]
@ypriverol I can look into updating the versions used, have updates to
xxindex and jmzidentml allowed it to read mid files >2GB?

On Jun 29, 2017 12:43 AM, "Yasset Perez-Riverol" <notifications@github.com>
wrote:

@JB-MS <https://github.com/jb-ms> @FarmGeek4Life
<https://github.com/farmgeek4life> we have a native converter of mzIDentML
to mzTab (tab delimited files). Another possible solution. Have you try to
increase the version of jmzIdentML. We did major improvements in the
performance of the library.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sangtaekim/msgfplus/issues/14#issuecomment-311888658>,
or mute the thread

**Comment by ypriverol** [comment]
I have try files of more that 2GB and it works, but please let me know if it does not work and we can try to improve the performance more.

**Comment by JB-MS** [comment]
@FarmGeek4Life Using Mono, the MzidToTsvConverter converter works also fine on macOS Sierra and CentOS 7. Thanks! I will test it also with the large files.

@ypriverol  I'll look also into the jmzIdentML library. Thanks!

**Comment by FarmGeek4Life** [comment]
@ypriverol What has changed between version 1.2.4 of jmzidentml and 1.2.6 that yields performance improvements? Looking at the commit history I see unit tests and pom.xml modifications for it and xxindex 0.17 to 0.20, which I wouldn't think would give performance improvements unless they are coming from other dependencies.

**Comment by JB-MS** [comment]
@FarmGeek4Life 

I have used the C# MzidToTsvConverter and it is really pretty fast! I have still a problem with the results and it may be a general bug. The columns 'SpecID' and 'ScanNum' refer to the same number. If iI understand it correctly, 'ScanNum' should be the ID in the spectrum (mgf) file and 'SpecID' the ID in the mzid file? If i use the Java based converter (edu.ucsd.msjava.ui.MzIDToTsv) of the MS-GF+ jar, the 'ScanNum' refers to the correct Spectrum in the mgf. I have converted mzid files from the MG-GF+ versions 2016_09_16 and 2017_01_27 and the problem occurs with both files.

Thanks for your help.

Cheers,
Johannes

**Comment by FarmGeek4Life** [comment]
@JB-MS it is a bug, and it has already been fixed in the library used to
read mzidentml; I need to update libraries for the converter, recompile,
and upload the new version.

**Comment by FarmGeek4Life** [comment]
I uploaded a new version of MzidToTsvConverter at https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/releases/tag/v1.0_20170704 

Only difference is the updated mzIdentML parsing library (the version at omics.pnl.gov is not updated yet).

**Comment by JB-MS** [comment]
@FarmGeek4Life Thanks for the super quick fix!

It works now fine!

Just out of pure curiosity: Do you plan to adapt the converter, so that it can convert also mzid files originating from other database search engines? Or is it already implemented?

Cheers,
Johannes

**Comment by FarmGeek4Life** [comment]
@JB-MS at the moment there are no plans to do so, though I don’t think it would be much work to output to the more generic mzTab format as an option for any mzid file. Right now it shouldn’t crash when run on non-MS-GF+ mzid files, just several columns will be empty because there is no mapping for other search engines’ scores.

**Comment by ypriverol** [comment]
Hi:
 We have a converter from mzidentml to mztab format, that is used in production in PRIDE. We are working in the performance for big mzidentml. now.

**Comment by FarmGeek4Life** [comment]
Wait - I just looked at the mzTab specification, and adding conversion to a full mzTab file is not what I had in mind; instead I was thinking of a tab-separated format where the score columns change in heading and count for different search engines.

**Comment by JB-MS** [comment]
@FarmGeek4Life 

Unfortunately, i still have problems during mzid conversion. I am using MS-GF+ version 2017/01/27 . The C# converter (version 2017/07/04) throws the following error:

```
unroll results: False
show decoy: False
single result per spectrum: False
Conversion failed: An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException (System.ExceptionResource resource) [0x0000b] in <f712f98eb8e445c8918edaf595bbe465>:0
at System.Collections.Generic.Dictionary`2[TKey,TValue].Insert (TKey key, TValue value, System.Boolean add) [0x0008e] in <f712f98eb8e445c8918edaf595bbe465>:0
at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <f712f98eb8e445c8918edaf595bbe465>:0
at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadPeptideEvidence (System.Xml.XmlReader reader) [0x000d3] in <c35e318121b24d90a706f5888e0514ce>:0
at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadSequenceCollection (System.Xml.XmlReader reader) [0x00098] in <c35e318121b24d90a706f5888e0514ce>:0
at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadMzIdentMl (System.Xml.XmlReader reader) [0x001f5] in <c35e318121b24d90a706f5888e0514ce>:0
at PSI_Interface.IdentData.SimpleMZIdentMLReader.Read (System.String path, System.Threading.CancellationToken cancelToken) [0x00079] in <c35e318121b24d90a706f5888e0514ce>:0
at MzidToTsvConverter.MzidToTsvConverter.ConvertToTsv (System.String mzidPath, System.String tsvPath, System.Boolean showDecoy, System.Boolean unrollResults, System.Boolean singleResult) [0x00005] in <aa4e31edbbde478ea61c353a0c4310ee>:0
at MzidToTsvConverter.MzidToTsvConverter.ConvertToTsv (MzidToTsvConverter.ConverterOptions options) [0x0001f] in <aa4e31edbbde478ea61c353a0c4310ee>:0
at MzidToTsvConverter.Program.Main (System.String[] args) [0x00026] in <aa4e31edbbde478ea61c353a0c4310ee>:0
```

Cheers and thanks,
Johannes

**Comment by FarmGeek4Life** [comment]
Okay, that would be a bug in MS-GF+ - the 'key' mentioned is the 'id' attribute to the PeptideEvidence, and is supposed to be unique within the file (per the mzIdentML specification). The PeptideEvidence ID was originally just a numeric increment, but was changed due to a request from someone that wanted to more easily match identifications between different searches. Given the current method of creating those IDs, a collision should only occur if it is the same protein, peptide (including dynamic modifications), and offset in the protein. Is this occurring for only one file, or for many of them?

**Comment by zrolfs** [comment]
I'm encountering a similar issue, where I'm using MS-GF+ through PeptideShaker's SearchGUI:
Conversion failed: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadPeptideEvidence(XmlReader reader) in I:\Jenkins\jobs\PSI_Interface\workspace\PSI_I                nterface\IdentData\SimpleMZIdentMLReader.cs:line 936
   at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadSequenceCollection(XmlReader reader) in I:\Jenkins\jobs\PSI_Interface\workspace\PS                I_Interface\IdentData\SimpleMZIdentMLReader.cs:line 840
   at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadMzIdentMl(XmlReader reader) in I:\Jenkins\jobs\PSI_Interface\workspace\PSI_Interfa                ce\IdentData\SimpleMZIdentMLReader.cs:line 673
   at PSI_Interface.IdentData.SimpleMZIdentMLReader.Read(String path) in I:\Jenkins\jobs\PSI_Interface\workspace\PSI_Interface\IdentData\S                impleMZIdentMLReader.cs:line 591
   at MzidToTsvConverter.MzidToTsvConverter.ConvertToTsv(String mzidPath, String tsvPath, Boolean showDecoy, Boolean unrollResults) in F:\                My Documents\Projects\Bryson_Gibbons\MzidToTsvConverter\MzidToTsvConverter\MzidToTsvConverter.cs:line 20
   at MzidToTsvConverter.MzidToTsvConverter.ConvertToTsv(ConverterOptions options) in F:\My Documents\Projects\Bryson_Gibbons\MzidToTsvCon                verter\MzidToTsvConverter\MzidToTsvConverter.cs:line 14
   at MzidToTsvConverter.Program.Main(String[] args) in F:\My Documents\Projects\Bryson_Gibbons\MzidToTsvConverter\MzidToTsvConverter\Prog                ram.cs:line 21

**Comment by FarmGeek4Life** [comment]
The [Latest Release](https://github.com/sangtaekim/msgfplus/releases/latest) (v2017.08.23) of MS-GF+ should fix this issue last issue, unless it is because of different modifications of near-identical mass that can affect the same residue.

**Comment by LeiWang-IUB** [comment]
Hey there,

I used the MSGF C# MzidToTsvConverter and it works very fast! The only thing is that I didn't find column 'Title' in the generated .tsv file. It would be great if we could have Title back since it is more easier to locate a spectrum by name instead of index.  Is it possible that you can add this function?  Thanks very much!

**Comment by alchemistmatt** [comment]
I do not understand the question.  What data do you expect to see in the Title column.  The columns produced by the C# MzidToTsvConverter converter include the following (with example values shown):

| #SpecFile | SpecID | ScanNum | FragMethod |
|----|----|----|----|
| QC_PP_MCF-7_17_02-run1_16Dec17_Elm_AQ-17-10-02.mzML | controllerType=0 controllerNumber=1 scan=16231 | 16231 | HCD |
|QC_PP_MCF-7_17_02-run1_16Dec17_Elm_AQ-17-10-02.mzML | controllerType=0 controllerNumber=1 scan=3068 | 3068 | HCD |

The columns produced via 
`java.exe -Xmx3500M -cp MSGFPlus.jar edu.ucsd.msjava.ui.MzIDToTsv -i SearchResults.mzid` 
are the same -- no title column.  Finally, examining a .mzid file, I don't see any title column.  The closest I can think you mean is the SpecID column, which refers to `spectrumRef` values in the source .mzML file, for example
`<spectrum index="22093" id="controllerType=0 controllerNumber=1 scan=22094" defaultArrayLength="101">`

**Comment by alchemistmatt** [comment]
Thinking about this more, I suspect your input file is a Mascot Generic file (.mgf), which can have a `TITLE` tag for each mass spectrum.  The question is, how is that data encoded in the .mzid file produced by MSGF+; it's probably lost.  I suggest, if possible, that you instead use .mzML files as your input files

**Comment by LeiWang-IUB** [comment]
Hi alchemistmatt,

Thanks for your quick reply!  I did use the MGF file as my input.  One more question is that I tried to use the C# MzidToTsvConverter to convert a mzid file more than 16GBs to tsv file and it kept running over 12 hours.  My desktop has 16GB memory, so I think maybe in your program you tried to read all mzid to memory at once?  Is there anyway to get around it?

Thanks very much,
Lei

**Comment by LeiWang-IUB** [comment]
I made it by running it in Linux using mono, thanks!

**Comment by alchemistmatt** [comment]
Good to hear it worked with Mono.  The largest .mzid file I've seen is around 18 MB when gzipped, or ~200 MB when decompressed.  If you're working with single .mzid files on the 16 GB size range, that is far bigger than I would have expected.  Did you combine several instrument runs together into a single file and then searched that file with MSGF+?  Regardless, the present version of MzidToTsvConverter does need to load the entire .mzid file into memory.  However, we have some ideas on how to decrease the memory footprint and will pursue those soon.

**Comment by LeiWang-IUB** [comment]
Hi Matthew,

You are absolutely right.  I combined several mgf files into one single file and then searched it against MSGF+.  Quite lucky to get around this problem using Mono!

Thanks a lot!

**Comment by FarmGeek4Life** [comment]
[Release 1.2.0 of MzidToTsvConverter](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/releases/tag/v1.2.0) should reduce the memory footprint significantly for large mzid files. It only holds one spectrum-peptide match in memory at a time, rather than loading all of them (with their accompanying extra data) into memory before writing any results.
